services:
app:
# Asegúrate de que esta sea la imagen de tu repo: hogwarts_backend_991
image: ghcr.io/jmarthy7/hogwarts_backend_991:latest
container_name: aaee_hogwarst_app_jmb
restart: always
ports:
- "8080:8080" # El puerto que usa tu API
env_file:
- .env
